remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Mattéo Dewaegheneire"
description: "Portfolio"
name: "Mattéo Dewaegheneire"
show_downloads: false
github:
  is_project_page: false
page.title: "Mattéo Dewaegheneire"
