remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - assets/style.css
title: "Mattéo Dewaegheneire"
description: "Développeur Full Stack Junior"
name: "Mattéo Dewaegheneire"
show_downloads: false
github:
  is_project_page: false
page.title: "Mattéo Dewaegheneire"
